services:
  backend:
    build:
      context: ./uvicorn-server
      dockerfile: Dockerfile

    container_name: cartridgemaster-backend

    restart: unless-stopped

    env_file:
      - .env

    environment:
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8080"
      TZ: "Europe/Moscow"

    volumes:
      - ./data:/data

    expose:
      - "8080"

    networks:
      - cartridgemaster-network


  caddy:
    image: caddy:latest

    container_name: cartridgemaster-caddy

    restart: unless-stopped

    depends_on:
      - backend

    environment:
      SITE_ADDRESS: "${SITE_ADDRESS}"
      TZ: "Europe/Moscow"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./caddy-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - cartridgemaster-network


networks:
  cartridgemaster-network:
    driver: bridge


volumes:
  caddy_data:
  caddy_config: